# Generated by Django 5.1.1 on 2024-09-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_order_shipping_address_order_shipping_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_ward',
            field=models.CharField(max_length=100),
        ),
    ]
